### ISSUE TITLE
Combine with co-body

### ISSUE THREAD

**Issue by ruimarinho** [koajs/bodyparser#10]
@dead-horse I think that the line between this package and co-body is getting increasingly thinner. Some patches, like the one that adds support for json-patch, was initially targeted for co-body and then moved and merged here. The code surface covered by co-body is really small. Would you accept a PR that ports its features to here?

**Comment by dead-horse** [comment]
go ahead!

**Comment by fengmk2** [comment]
:+1:

**Comment by ruimarinho** [comment]
Closing this as `co-body` has been moved to the `cojs` organization. If you think it still makes sense, let me know.
