### ISSUE TITLE
parse query string

### ISSUE THREAD

**Issue by Ali-Azmoud** [koajs/bodyparser#100]
Hi

I can't parse a request like this. bodyparser returns `{}`

    http://localhost:5000/admin/product/new?name=Handmade%20Plastic%20Chicken&meta_keywords=Handmade%20Frozen%20Keyboard%20Creative%20Regional

This is my configuration in app.js file

    app.use(bodyParser({
        strict: false,
        enableTypes: ['json','form','text']
    }));

**Comment by dead-horse** [comment]
no, koa-bodyparser won't parse querystring, you can directly use `ctx.query`
