### ISSUE TITLE
`extendTypes` error

### ISSUE THREAD

**Issue by TerenceZ** [koajs/bodyparser#11]
If we extends the type by options, we will get errors reported by `type-is` module, when I look into the source code, I find the issue is the `extendType` function:
```js
function extendType(original, extend) {
  if (extend) {
    if (!Array.isArray(extend)) extend = [extend];
    extend.forEach(original.push.bind(original));
  }
}
```
After push a extended types `{json:["app/x", "app/y"]}`, the `original` will become
```json
[
// default
0,
"app/x",
["app/x", "app/y"],
1,
"app/y",
["app/x", "app/y"]
]
```
If the check for `app/x` succeeds, it will be ok. But if fails or check for `app/y`, it will throw an error.

In addition, the test passes because just only test the 'app/x'. If we modify the test for `extent type should extent json ok` to

```js
      request(app.listen())
        .post('/')
        .type('application/y-javascript')
        .send(JSON.stringify({ foo: 'bar' }))
        .expect({ foo: 'bar' }, done);
```
The test will fail.

**Comment by dead-horse** [comment]
oops
