### ISSUE TITLE
Form-data is still not available?

### ISSUE THREAD

**Issue by tdimnet** [koajs/bodyparser#117]
Hello there,

I am trying to use form-data on a back-end api and it seems it still does not work. I saw a PR but it closed since months.

Do you have any update?

Regards.
Thomas.

**Comment by dead-horse** [comment]
can you provide some more informations to let us know what the situation you are facing?

**Comment by mgildea** [comment]
body-parser is returning an empty ctx.request.body object for myself as well when type:"multipart/form-data".  
I also see the still open pull request from 2017:
https://github.com/koajs/bodyparser/pull/91

Is there a plan to merge this? or to implement parsing form data another way?

**Comment by tdimnet** [comment]
With some delay I decided to use another method by using our S3 buckets.
@mgildea : I don't know if this library is maintained anymore :/

**Comment by chobits4** [comment]
- `ctx.request.body` 无法正常拿到数据，是因为`egg.js`  内置了`bodyparser`插件，而这个插件是不支持`form-data`编码数据的
- 所以这个插件本身有问题，要解决这个问题，要么使用`x-www-form-urlencoded` 发起请求，要么就换成支持`form-data`的插件，比如`koa-body`

**Comment by niftylettuce** [comment]
Please use `@koa/multer` instead at https://github.com/koajs/multer
