### ISSUE TITLE
Can resolve to normal parameter type

### ISSUE THREAD

**Issue by yoonasy** [koajs/bodyparser#118]
#### set request
`content-type': 'application/x-www-form-urlencoded; charset=UTF-8`

![image](https://user-images.githubusercontent.com/24489180/50818718-d56e2900-1362-11e9-8688-f938d5033e71.png)

#### koa
```
app.use(cors())
app.use(bodyParser())
app.use(registerRouter())

...
router.all('/addItem', async (ctx, next) => {
  let { parentID, type, content } = ctx.request.body
  console.log(ctx.request.body)
  ctx.body = ''
})
```

#### result
```
{
  parentID: '1',
  type: '0',
  content:
  {
    isExpand: 'true',
    name: '测试'
  }
}
```

The `isExpand` type should be a Boolean value，But it‘s strings，Excuse me, what should I do

**Comment by dead-horse** [comment]
if you want to keep params' type, you should use `application/json` format. `application/x-www-form-urlencoded` is a string base protocol, it can't keep params' type

**Comment by yoonasy** [comment]
@dead-horse  但是 使用`application/json` 他传递的是`query`字符串

超级感谢大佬 解决了

![image](https://user-images.githubusercontent.com/24489180/50824510-bf1b9980-1371-11e9-9261-902e1f8adb7d.png)

是我`axios` 将`data`转换成`query`参数了 `qs.stringfy(data)`

之前用的`.net`后台 他们后台能直接解析 想着bodyparser也能解析

![image](https://user-images.githubusercontent.com/24489180/50824688-37825a80-1372-11e9-82d3-5927633b36af.png)
