### ISSUE TITLE
Getting req.body from POST Body occurs an Error " stream.on is not a function when using turbo-http

### ISSUE THREAD

**Issue by nassirdreffy** [koajs/bodyparser#119]
const bodyParser = require('body-parser');
const server = require('restana/libs/turbo-http') 
const router = require('find-my-way') 
const routerFactory = (options) => {return router(options)}

const service = require('restana')({routerFactory, server* });
 **//server occurs an error:**

> {
    "errClass": "TypeError",
    "code": 500,
    "message": "stream.on is not a function"
}

service.start(3000)
service.use(bodyParser.json());
service.use(bodyParser.urlencoded({extended:true}));

service.get('/', async (req, res) => {
    res.send("Hello World");
});
service.get('/user/:id', async (req, res) => {
    res.send("User ID: " + req.params.id);
});
service.post('/user', async (req, res) => {
    res.send(req.body.name);
});

/#################################################################

Regards

**Comment by dead-horse** [comment]
hi, I'm not sure if koa-bodyparser can work with `restana`. If you want to investigate the error, you should first look at the error stack to find where the error occured.
