### ISSUE TITLE
co-busboy does not work very well for koa2

### ISSUE THREAD

**Issue by flyingrx** [koajs/bodyparser#140]
co (generator function and yield) syntax is mandatory with co-busboy.
It is not user-friendly. Maybe it is not suggested in the README.

**Comment by flyingrx** [comment]
![image](https://user-images.githubusercontent.com/17722981/95950645-81da1a80-0e27-11eb-981e-70abc6263bf3.png)
too obsolete package

**Comment by 3imed-jaberi** [comment]
solved in the latest releases
