### ISSUE TITLE
XML Documentation Incorrect

### ISSUE THREAD

**Issue by Naismith** [koajs/bodyparser#141]
The current readme indicates this library supports XML for types, limits and extending but in fact does not. This also contradicts with the typescript definitions from @types/koa-bodyparser.

**Comment by Abramovick** [comment]
@Naismith did you ever find any solutions for this?

**Comment by 3imed-jaberi** [comment]
@Naismith, can you provide more information about the issue? if your problem is related only to types, you can extend the current request interface.

**Comment by 3imed-jaberi** [comment]
I'll close this issue, feel free to ping me or re-open it.
