### ISSUE TITLE
Why is body typed as string? gives tsc compilation errors

### ISSUE THREAD

**Issue by maapteh** [koajs/bodyparser#142]
Why is this library not self typed. Now the type definition somewhere else is like:

```
declare module 'koa' {
    interface Request {
        body: string | Record<string, unknown>;
        rawBody: string;
    }
}
```

_It seems i have to drop it at https://www.npmjs.com/package/@types/koa-bodyparser_

**Comment by tsejerome** [comment]
Hello there, can you share how did you manage to resolve this issue?

**Comment by maapteh** [comment]
Hi, i pinned it to version `4.3.0` untill its fixed correctly :)

**Comment by nicolasespiau** [comment]
For now I use only application/json bodies so I did that:
```javascript
const myInternalVar:MyInternalType = JSON.parse(ctx.request.rawBody);
```

It's ugly but it works.
