### ISSUE TITLE
Rewrite to TypeScript

### ISSUE THREAD

**Issue by pkuczynski** [koajs/bodyparser#143]
@dead-horse I would be keen to rewrite this library to TypeScript. Would you be interested?

**Comment by pkuczynski** [comment]
Seems that @dead-horse does not have time to respond. @fengmk2 @haoxins @jonathanong what do you think?

**Comment by jonathanong** [comment]
I personally don't use this... did you try pinging him on Twitter?

**Comment by vanthome** [comment]
I wounder whether this project is even still alive?

**Comment by 3imed-jaberi** [comment]
[This happen in 2023](https://github.com/koajs/bodyparser/pull/152) 😅, feel free to share your ideas there.

**Comment by fengmk2** [comment]
https://github.com/koajs/bodyparser/pull/152
