### ISSUE TITLE
[FR] Recommend koajs/koa-body instead of co-busboy for multipart

### ISSUE THREAD

**Issue by FossPrime** [koajs/bodyparser#144]
co-busboy has poor ergonomics for koa use and requires a stack of app level dependencies to handle multipart forms. Meanwhile, the formidable based, streaming, first party koajs/koa-body exists...

https://github.com/koajs/koa-body
Sandbox: https://codesandbox.io/s/koa-body-upload-tt3c2
https://www.npmjs.com/package/formidable
https://stackoverflow.com/questions/55872109/how-to-upload-file-using-koa

## How express deals with it:
https://expressjs.com/en/resources/middleware/body-parser.html
![Screenshot from 2021-10-19 06-50-16](https://user-images.githubusercontent.com/876076/137903761-55ba2160-6e2a-4f9b-8159-48e8f3f136ce.png)

**Comment by 3imed-jaberi** [comment]
In the near future, we will update our documentation, where we will add more information about all aspects to build a backend. 

In the current stage, I recommend to useone of these modules; 
- koa-bodyparser (didn't support form-data)
- koa/multer (support only form-data)
- koa-body
