### ISSUE TITLE
[fix] Type disagreement between `koa-body` and `@types/koa-bodyparser`

### ISSUE THREAD

**Issue by maslade** [koajs/bodyparser#150]
## Describe the bug

**Node.js version:** 16

**OS version:** OSX 11.6.4

**Description:** Types are incompatible between these two projects. From some investigating, it looks like this has been a recurring off-and-on problem that was [reintroduced via the DefinitelyTyped project](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61549) about a week ago.

I started a discussion on that project board but it's tumbleweeds at the moment, so I thought I'd raise it here as well, but feel free to close if this is the wrong place. I'm mostly looking for guidance and would be happy to submit a PR to fix.

https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/62237

## Actual behavior

Type error:

```
#17 221.7 node_modules/@types/koa-bodyparser/index.d.ts(25,9): error TS2717: Subsequent property declarations must have the same type.  Property 'body' must be of type 'any', but here has type 'Record<string, unknown> | undefined'.
```

## Expected behavior

No type error between latest versions of `koa-body` and `koa-bodyparser`.

## Code to reproduce

```
// Step 1. `npm install koa-body koa-bodyparser @types/koa-bodyparser@latest typescript`
// Step 2: `npx tsc example.ts`
import {} from 'koa-body';
```

## Checklist

- [X] I have searched through GitHub issues for similar issues.
- [X] I have completely read through the README and documentation.
- [X] I have tested my code with the latest version of Node.js and this package and confirmed it is still not working.

**Comment by megakoresh** [comment]
This should definitely be fixed

**Comment by alifarooq0** [comment]
Running into the same issue. Any workaround for this?

**Comment by 3imed-jaberi** [comment]
Hey guys, I would mention that I have [re-created the module with TS](https://github.com/koajs/bodyparser/pull/152/checks?check_run_id=12430547948) so no need to `@types/koa-bodyparser` in the future.


For quick solution about the typing behave, you can override the request signature like this

```ts
declare module "koa" {
    interface Request {
        body?: Record<string, unknown>; // BTW, you can override it to any type you want ... 
        rawBody: string;
    }
}
```
