### ISSUE TITLE
[fix]  npm 和 github README不一致。

### ISSUE THREAD

**Issue by RSS1102** [koajs/bodyparser#158]
![8e775fbbb94f4e5f392d20e02bd5878](https://github.com/koajs/bodyparser/assets/81673017/c6db6e14-252a-4dc4-8f46-a96db32a60ba)

![729023625c7d4a3724f5d937da9e17e](https://github.com/koajs/bodyparser/assets/81673017/f31ffaea-ea46-41e7-87bd-a9202bd9c5e3)

**Comment by 3imed-jaberi** [comment]
It's a different URL path restriction between platforms!
