### ISSUE TITLE
how to detect invalid JSON and response some helpful message?

### ISSUE THREAD

**Issue by eisneim** [koajs/bodyparser#18]
some guy may try to post some wired string and set header to be json, i can caught the error but don't know how to response a custom message that tell them," dude, your json is invalid !"

i tried something like this:
```javascript
app.use(function*(next){
    if(/get|delete|head/i.test(this.method)) return yield next;
    if( /json/i.test( this.get('Content-Type') ) ){
      try{
        require('co-body').json(this)()....... blah blah blah.....
      }catch(e){
         
      }
    }
    
    yield bodyParser({
      formLimit: '200kb',
      jsonLimit: '1mb',
    }).call(this,next)
  });

```

i looked the source code, there is no error handling;

**Comment by dead-horse** [comment]
https://github.com/cojs/co-body/blob/master/lib/json.js#L36

error is thrown here, you can add this in your custom error handler:

```js
try {
   yield bodyParser({
      formLimit: '200kb',
      jsonLimit: '1mb',
    }).call(this,next)
} catch (err) {}
```

**Comment by eisneim** [comment]
stupid me!! just after i post the issue , i realized i can do it in that way! thanks anyway

**Comment by eisneim** [comment]
this method will also have a problem, it will caught not only the JSON parse error but all the nested middleware's error and router's error , which means,   app.on('error') will become useless.

how to make this better?

**Comment by dead-horse** [comment]
maybe we can add `options.onerror` for `koa-bodyparser` to support custom error handler?

**Comment by eisneim** [comment]
it would be great ! my current solution is:
 add global error handler and check error type 

```javascript
if((err instanceof SyntaxError) && err.body ){
	error = {
		msg:'JSON对象语法错误，请检查',
		detail: err.toString(),
	}
}
		
```

**Comment by dead-horse** [comment]
https://github.com/koajs/bodyparser/commit/194181298fe3bffce6b5fcf3cfebc35b8cda6c89

**Comment by dead-horse** [comment]
`koa-bodyparser`@1.6.0

**Comment by eisneim** [comment]
pretty efficient!
