### ISSUE TITLE
Is `null` a valid body?

### ISSUE THREAD

**Issue by RHavar** [koajs/bodyparser#19]
I'm starting to think my fix in issue #14 was a bit off. Originally the idea was make it so `this.body.foo`  was always safe and would never throw, however I've run into a case that breaks that. Someone can send the json body  `null`, which we put in `this.body`  which makes  `this.body.foo` throw.

The two fixes I can think, is we never allow `null` as a body, and convert it to `{}` or maybe revert #14 and document that  `this.body.foo` is not "safe" unless you check the existence of `this.body` first

**Comment by dead-horse** [comment]
make `this.body` always be object looks fine to me

**Comment by RHavar** [comment]
What about cases, where the body is a value? e.g.  `"FOO"`

**Comment by dead-horse** [comment]
at least it won't throw when do `this.request.body.foo`, maybe we can 

1. document `this.requset.body` will not always be object when use json parser.
2. convert null to `''` or `{}`, make sure `this.request.body.foo` never throw.

**Comment by dead-horse** [comment]
another solution: throw `invalid json` error when json parse return non-object.

**Comment by RHavar** [comment]
I'm not sure if the last one is a good ideas, as `"foo"` is actually a valid json body, even though it's not an object.

I think 1. is the most pure solution, and 2. is the most convenient to use

**Comment by coderhaoxin** [comment]
> as "foo" is actually a valid json body

`JSON.parse("foo")` will throw error

I think it's a good idea to convert `null` to `{}`,
also `"0" => {}`, maybe.

**Comment by RHavar** [comment]
> JSON.parse("foo") will throw error

No it won't, you just don't have the `"` in the string. Try:
````
> JSON.parse('"foo"')
'foo'
```

**Comment by RHavar** [comment]
My preference, for purity would be:

`this.body == undefined`  When there is no body, or the body was invalid
`this.body == null`   When the request has explicitly sent `null` as the body
`this.body == 0`  When the request has explicitly sent `0` as the body
`this.body == { ... } `  When the request has sent a json body


An unfortunate consequence, is people must explicitly test to avoid throwing:

`if  (this.body && this.body.foo == ....)`

**Comment by dead-horse** [comment]
from the [rfc](http://www.ietf.org/rfc/rfc4627.txt), `application/json` body must be array or object, so we should throw when body is not an object.

**Comment by RHavar** [comment]
Oh nice, I didn't know that. That makes it quite easy then
