### ISSUE TITLE
this.req._readableState.ended is true

### ISSUE THREAD

**Issue by optikalefx** [koajs/bodyparser#23]
I'm not quite sure how to replicate  yet, this has been happening every so often on my project. I'm using emberjs and a normal run of the mill POST to my server which is running koa.

Nothing out of the ordinary it would seem http://cl.ly/image/1Z2a332O2U3v

But in koa, `this.request.body` is undefined. 

I did some digging and the reason the body is not getting parsed is because 1) this.request doesn't have my JSON for some reason and 2) `this.req._readableState.ended` is true.

Again, the ajax call is very standard

```
let ajaxOptions = {
	url,
	data,
	method,
	xhrFields: {
		withCredentials: true
	}
};
// if POST or PUT
ajaxOptions.contentType = 'application/json';
ajaxOptions.data = JSON.stringify(ajaxOptions.data);
```

Any idea what could cause the JSON body to not show up in koa? It's obviously being sent by the browser as seen in that chrome screenshot. http://cl.ly/image/1Z2a332O2U3v

**Comment by optikalefx** [comment]
I checked `req` as well and nothing is there for my data either. Again, this isn't an always things, I feel like if I restart everything, chrome included and the server it would be ok. I'll give that a try and see, but I do keep getting stuck in this state from time to time

**Comment by optikalefx** [comment]
Also to note, after a restart of chrome, ember and koa i'm still in this weird state of unable to POST data.

**Comment by dead-horse** [comment]
can you post you code?

`this.request.body` will never be `undefined`, see

https://github.com/koajs/bodyparser/blob/master/index.js#L71
https://github.com/cojs/co-body/blob/master/lib/json.js#L55

**Comment by optikalefx** [comment]
@dead-horse ok, so this probably has to do with coding at 2am, but somehow i've been actually using this other package https://www.npmjs.com/package/koa-body-parser that is buggy and old. Not sure how that happened.

Once I changed to this repo all is good.
