### ISSUE TITLE
Query strings are not parsed as arrays

### ISSUE THREAD

**Issue by optikalefx** [koajs/bodyparser#24]
If I do a GET request and pass an array, the browser sends it over as id[] id[] as expected. But koa parser doesn't see it as an array. It comes through as

```
qs { 'ids[]': 
   [ '55fb67079a5940a6ac32ab08',
     '5606eadad5689ece061d726b',
     '5606ebfa4c872978085c325f' ] }
```

Chrome screenshot 
![image](https://cloud.githubusercontent.com/assets/926885/10596877/004b676a-76b7-11e5-8d57-d0934ceecca5.png)

**Comment by dead-horse** [comment]
`bodyparser` only parse http request body, you can checkout https://github.com/koajs/qs

**Comment by optikalefx** [comment]
Thanks!
