### ISSUE TITLE
ctx.req.body = ctx.request.body

### ISSUE THREAD

**Issue by niftylettuce** [koajs/bodyparser#33]
Can we change it so we can access on `ctx.req.body` as well? https://github.com/koajs/bodyparser/blob/3.x/index.js#L59

**Comment by dead-horse** [comment]
I think we should not change the original http request, in what situation we can't get body from `ctx.request` ?

**Comment by niftylettuce** [comment]
i forget now :frowning:

**Comment by niftylettuce** [comment]
@dead-horse Oh, I was just making it a helper, like a shorter version.  Instead of typing `ctx.request.body` I could just type `ctx.req.body`.
