### ISSUE TITLE
What happend if a multipart form with file uploaded?

### ISSUE THREAD

**Issue by guileen** [koajs/bodyparser#4]
What happend if a multipart form with file uploaded?

**Comment by booxood** [comment]
Why not integrate `multipart form` support?

**Comment by tunnckoCore** [comment]
lol, cuz' we have side projects which support these + multipart, just use them.

Talking especially for `koa-better-body`, in which was added `extendTypes option` in latest release.

**Comment by booxood** [comment]
@tunnckoCore  Replaced `koa-better-body`, can't test ok.
Because parsed `json` and `urlencoded` value assign to request.body.fields.

**Comment by booxood** [comment]
`koa-body` is a choice. But have a issue when a input select multiple files.
I made a PR for the issue.

**Comment by tunnckoCore** [comment]
koa-better-body have more features and cover most use-cases.

> Because parsed json and urlencoded value assign to request.body.fields.

For that reason we have options for this. And yea, its **better** than koa-body.

**Comment by booxood** [comment]
@tunnckoCore Ok, I will try.
