### ISSUE TITLE
koa-bodyparser cannot  recognize content-type with charset

### ISSUE THREAD

**Issue by leim** [koajs/bodyparser#50]
When i am using koa-bodyparser, it works well with 'Content-Type': 'application/json', but when the request's 'Content-Type' is 'application/json;charset=utf-8', its body cannot be parsed and i get only a {}
 Here below is a screenshot of both situation. thanks.

![aaaa](https://cloud.githubusercontent.com/assets/1665397/16576264/8b54cdbc-42c0-11e6-90c0-33c924e7906b.png)

**Comment by dead-horse** [comment]
it should support both, can you give us a example to reproduce it ?

**Comment by leim** [comment]
@dead-horse  I have posted an image of both situations, please check it, thanks.

**Comment by dead-horse** [comment]
please post server-end code here

**Comment by dead-horse** [comment]
it's fine to request https://github.com/koajs/bodyparser/blob/master/example.js with `content-type: application/json;charset=utf-8`

```bash
$ curl http://localhost:3000 -X POST -H 'content-type: application/json;charset=utf-8' -d '{"foo":"bar"}'
{"foo":"bar"}
```

**Comment by leim** [comment]
@dead-horse  I have found the problem, if 'Content-Type' is 'application/json;charset=utf8', it works well, but if 'Content-type' is 'application/json;charset=utf-8;' , there will be the problem, also if 'Content-Type' is 'application/json;' , there will be the same problem.
It is all about the semicolon, if 'Content-Type' end with a semicolon, the koa method ctx.is will not work.

**Comment by dead-horse** [comment]
https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.7

because this is an invalid `media types`

**Comment by leim** [comment]
@dead-horse Thanks.
