### ISSUE TITLE
koa@next doesn't support text

### ISSUE THREAD

**Issue by felixsanz** [koajs/bodyparser#52]
https://github.com/koajs/bodyparser/blob/next/index.js

It doesn't support `['text']`

**Comment by pleerock** [comment]
+1 having same issue

```typescript
const koa = require("koa");
const bodyparser = require("koa-bodyparser");
const router = require("koa-router")();

const app = new koa();
app.use(bodyparser());

router.post("/users", function(ctx: any) {
    console.log(ctx.request.body);
});

app
    .use(router.routes())
    .use(router.allowedMethods());

app.listen(3000);
```
request headers:
`Content-Type: text/plain; charset=utf-8` with text body.

console outputs: `{}`

**Comment by felixsanz** [comment]
There is a Pull Request here i think: https://github.com/koajs/bodyparser/pull/37/commits/05bf90e387abd9facc5bfe54d28729da338ef843

**Comment by dead-horse** [comment]
3.2.0
