### ISSUE TITLE
Parse JSON using the wrong method

### ISSUE THREAD

**Issue by maxming2333** [koajs/bodyparser#54]
`This module can parse point`

**Example：**

`request`

```
'{"a1": "xx", "a2": "cc.init"}'
```

`ctx.request.body`

```
{ '{"a1": "xx", "a2": "cc': { 'init"}': '' } }
```

but useing `JSON.parse`

```
{ a1: 'xx', a2: 'cc.init' }
```

**Comment by fengmk2** [comment]
What's the request headers?

**Comment by maxming2333** [comment]
sorry，i forget stick headers

![image](https://cloud.githubusercontent.com/assets/8816730/17655472/464b0d58-62e1-11e6-832a-465b60edbef5.png)

**Comment by maxming2333** [comment]
```
{"clz":"NGA","method":"callServer","args":{"api":"sdkjsse.imp","data":{"id":1471233745049,"data":{"type":"5","posIds":"1465376684310521","appId":"1000004121"}},"webViewId":"","async":true,"callbackId":"1"}}
```

U can see `sdkjsse.imp`

**Comment by fengmk2** [comment]
content-type is not json format, this request was parsed with form format https://github.com/koajs/bodyparser/blob/master/index.js#L88 , not json format.

**Comment by fengmk2** [comment]
You should set `Content-Type` header to `application/json`

**Comment by oleole90** [comment]
@fengmk2 how do I set content-type in koa?
