### ISSUE TITLE
Bodyparser causing 404 error if `await` is not used with `next` in any previous middleware

### ISSUE THREAD

**Issue by wlingke** [koajs/bodyparser#55]
For this simple koa2 server:

```
app.use(async (ctx, next) => {
  next();
});

app.use(bodyParser({ enableTypes: ['json'] }));
app.use(async (ctx) => (ctx.status = 200));

```

Client calls: 

```
fetch('/', {method: 'post', headers: {'Content-Type': 'application/json'}})
```

The return is status 404 - Not Found.

If I change  the first middleware by adding `await`:

```
app.use(async (ctx, next) => {
  await next();
});
```

then it works as expected.

**Comment by oleole90** [comment]
same here. Only works with `Content-Type: text/plain `

**Comment by dead-horse** [comment]
you **must** add `yield` before `next()` here, because bodyparser is asynchronous.
