### ISSUE TITLE
Verify function just like body-parser

### ISSUE THREAD

**Issue by alphanso** [koajs/bodyparser#56]
Hi,

I am switching from express to koa. I saw bodyparser for koa doesn't have verify function. Please consider this feature.

Thanks

**Comment by dead-horse** [comment]
it is not easy to add a verify function like express in `koa-bodyparser`, because we use `co-body` to handle the entire parse process. we must pass the verify function and request's context to `co-body`, so why do you need the verify function ?

**Comment by alphanso** [comment]
I am currently creating a messenger bot in koa. It gets a post request whenever it receives message from a user. I need to verify that request are actually coming from messenger platform only.

**Comment by dead-horse** [comment]
can't you verify request body after parse? If you need to access the raw request body, I think you can try https://github.com/stream-utils/raw-body to handle this all by yourself.

**Comment by alphanso** [comment]
raw-body takes a stream as a parameter which has already been processed by body-parser so it gives error. You will find more about this issue in given below SO question
http://stackoverflow.com/questions/32223947/access-the-raw-body-of-a-request-in-koa-js

```
  Error: request aborted
      at IncomingMessage.onAborted (/Users/rishabh/Workspace/coupon/node_modules/raw-body/index.js:269:10)
      at emitNone (events.js:86:13)
      at IncomingMessage.emit (events.js:185:7)
      at abortIncoming (_http_server.js:280:11)
      at Socket.serverSocketCloseListener (_http_server.js:293:5)
      at emitOne (events.js:101:20)
      at Socket.emit (events.js:188:7)
      at TCP._handle.close [as _onclose] (net.js:493:12)

```

**Comment by dead-horse** [comment]
i mean you should use raw-body instead of koa-bodyparser if you want to handle the raw request body.
