### ISSUE TITLE
post array more than 21

### ISSUE THREAD

**Issue by ahan** [koajs/bodyparser#57]
I have two Nodejs Apps: App A and App B
App A post array data to App B

Like this: 

```
let list = [ '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20' ]
request({
     method: 'POST',
     url,
     form: {
          list: list,
     }
}, function...)
```

App B get the array perfect
![screen shot 2016-10-21 at 6 10 48 pm](https://cloud.githubusercontent.com/assets/654880/19595087/cc98ec00-97ba-11e6-9760-c987d05655f9.png)

But if we change the "list" to a array, which length more than 21, something weird happened.

```
let list = [ '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21' ]
```

![screen shot 2016-10-21 at 6 09 57 pm](https://cloud.githubusercontent.com/assets/654880/19595078/c7727e26-97ba-11e6-93c3-d4291b468344.png)
App B get a array something like map.

I googled the keywords, like "post array 21", "post array to object", can't find useful infomations.

I kind of confused, is there anyone who know the reason about this?

Environment
Nodejs: v6.6.0
Koa: 2.0.0
koa-bodyparser:  3.2.0
Request: 2.74.0

**Comment by dead-horse** [comment]
please define your own rules by `options.querystring`, the default is https://github.com/ljharb/qs/blob/master/lib/parse.js#L7

**Comment by kmoe** [comment]
Automatically converting arrays longer than 20 into objects is highly unusual behaviour, and is likely to lead to a lot of bugs that are difficult to track down or don't appear in testing, when koa is used in more complex situations than the one above. It took me quite a while to find this issue after I noticed that some arrays I was sending to my koa server were not iterable for some reason.

Additionally, `options.querystring` is not documented in the README, though it documents other options. This will lead a reasonable reader to believe that the list of options in the README is exhaustive, and so they will not think to go looking in `parse.js` to find any other options.

I think this option should be removed (I will raise a PR for this), or at the very least, set to a sensible default (such as `Infinity`) and documented in the README.
