### ISSUE TITLE
POST json body isn't set on `ctx.request.body`

### ISSUE THREAD

**Issue by chovy** [koajs/bodyparser#59]
When I POST to my endpoint with a JSON body its not showing up on the server:

```
{
	"queries": ["pizza", "javascript"]
}
```

I get undefined for `ctx.request.body`

sending as form data seems to be ok for non-json objects. but I want to post json.

I've tried posting with both `application/javascript` and `application/json` neither work. (i'm using `"koa-bodyparser": "^3.2.0"` with `"koa": "^2.0.0",`)

Here is relevant app.js:

```
app
  .use(bodyParser())
  .use(cors({
    methods: ['GET', 'PUT', 'POST', 'PATCH', 'DELETE']
  }));

middleware(app);
routes(app);
```

**Comment by chovy** [comment]
My fault. Didn't define the content-type from Postman for "raw":

https://i.imgur.com/tKyEVnA.png

**Comment by liuhanqu** [comment]
i have meet with it too.  u should set request header correctly which means 'Content-Type' is equal to 'application/json'.

**Comment by elkarouani** [comment]
I added the content-type header, but it didn't work

**Comment by vocoWone** [comment]
i have meet too, i add koa-bodyparser

**Comment by AlexJubs** [comment]
I have the exact same issue. I'm using koa-body, and my request has the header `content-type: application/json`, yet the `ctx.request.body` is empty...
