### ISSUE TITLE
An error on onerror

### ISSUE THREAD

**Issue by felixsanz** [koajs/bodyparser#60]
When you pass `--header "Content-Encoding: fake"`, the `onerror` function doesn't get called. Looks like some inner library is just returning `< HTTP/1.1 415 Unsupported Media Type` by itself.

**Comment by felixsanz** [comment]
The problem is the **inflation** lib:

```javascript
  switch (encoding) {
  case 'gzip':
  case 'deflate':
    break
  case 'identity':
    return stream
  default:
    var err = new Error('Unsupported Content-Encoding: ' + encoding)
    err.status = 415
    throw err
  }
```

This code is what is causing an early return (the `default` case).

Why the bodyparser promise catch doesn't catch it?

**Comment by felixsanz** [comment]
I tried to fix it but too many magic libraries involved :( Can someone help please?

This is a workaround:

```javascript
  app.use(async (ctx, next) => {
    try {
      return bodyParser({
        enableTypes: ['text'],
        extendTypes: {
          text: ['text/html'],
        },
      })(ctx, next)
    } catch (err) {
      return ctx.throw(new Error('foo'), 400)
    }
  })
```

**Comment by dead-horse** [comment]
because bodyparser's onerror only catch the error thrown when parse the body, so it won't(and shouldn't) catch inflation's error.

this is not related with bodyparser, but if you want to ignore this error, you can try

```js
app.use(async (ctx, next) => {
  try {
    await next();
  } catch (err) {
    // your custom error handler
  }
});
app.use(bodyparser());
app.use(otherMiddleware());
```

**Comment by dead-horse** [comment]
@felixsanz I think this is co-body's bug that don't catch the error thrown in inflation, and this will be fix in https://github.com/cojs/co-body/pull/54, hope it won't break your code since I'll consider it as a bug fix.
