### ISSUE TITLE
Promise support

### ISSUE THREAD

**Issue by rapzo** [koajs/bodyparser#67]
Hey guys!

I see that `async` is widely used in here but wouldn't it be better to have a promise implementation until `async` is part of a node stable release?

https://github.com/koajs/bodyparser/blob/master/index.js#L69-L96

What are your thoughts on this?

**Comment by smcmurray** [comment]
async IS part of a node stable release.

**Comment by rapzo** [comment]
Heh. It is indeed!
I guess another upgrade has to be done.
Thanks!
