### ISSUE TITLE
fail to parse form data

### ISSUE THREAD

**Issue by smcmurray** [koajs/bodyparser#68]
Whenever I have my browser fetch('...', {method: 'POST', body: \<FormData\>}), koa-bodyparser fails to parse it.

\* \<FormData\> is an instance of FormData

**Comment by FebV** [comment]
same issue when POST by postman in form-data

**Comment by smcmurray** [comment]
It seems that the only supported formType in koa-bodyparser is application/x-www-form-urlencoded
FormData uses multipart/form-data

**Comment by dead-horse** [comment]
multipart is much more complex, it is hard to handle automatically, you can use [co-busboy](https://github.com/cojs/busboy) or [co-multipart](https://github.com/cojs/multipart) to process multipar body.
