### ISSUE TITLE
raw-body doesn't seem to work

### ISSUE THREAD

**Issue by felixsanz** [koajs/bodyparser#73]
I parsed the body and it works, but if i dump the rawBody i get nothing.

the order  was:

1. middleware
2. console log body <- works
3. console log rawBody <- nothing

**Comment by dead-horse** [comment]
can you provide the version and the minimum reproduce code?

**Comment by dead-horse** [comment]
it is ok in the test case: https://github.com/koajs/bodyparser/blob/master/test/middleware.test.js#L39

**Comment by felixsanz** [comment]
The version is latest, `4.2.0`.

The code... I sent a string compressed with gzip to koa, and the `body` had the string decompressed, but the `rawBody` had nothing (console.log it was giving me an empty new line). I was expecting a buffer (raw bytes of the compressed body)

**Comment by i5ting** [comment]
it will happen when no enableTypes matched in koa-bodyparser module

**Comment by stickyhands** [comment]
@i5ting do you think its normal ?
If for some reason bodyparser cant parse a format, why would it doesnt put it inside rawBody ?

**Comment by chovy** [comment]
I'm also getting undefined for rawBody.

**Comment by DMXL** [comment]
Same here. Parsed result was correctly presented, which means one of the enableTypes was hit, right?

**Comment by libook** [comment]
Happens to me.

I found that the request body is text;
and the parser doesn't process text on default.

The parser provided "enableTypes" option so that I can let it process text body.

```javascript
app.use(bodyParser({
        "enableTypes": ['json', 'form', 'text'],
    }));
```
