### ISSUE TITLE
Make compatible with node 6

### ISSUE THREAD

**Issue by sibelius** [koajs/bodyparser#76]
is this compatible with node 6?

```jsx
"engines": {
    "node": ">=7.6"
  }
```
https://github.com/koajs/bodyparser/blob/master/package.json#L42

I'm using here https://github.com/entria/graphql-dataloader-boilerplate

this code run with node 6 using babel, do you think we can lower the node engine requirement?

**Comment by sibelius** [comment]
can we use babel to provide compiled version of this project?

**Comment by dead-horse** [comment]
no, you can use [koa-bodyparser@3](https://github.com/koajs/bodyparser/tree/3.x)
