### ISSUE TITLE
can't install 

### ISSUE THREAD

**Issue by alichengyue** [koajs/bodyparser#81]
when i was run 
npm install koa-bodyparser --save
it show that:
no such file or directory, stat 'file:node_shrinkwrap/co-4.6.0.tgz'
how i install koa-bodyparser
thx

**Comment by dead-horse** [comment]
i think it is not koa-bodyparser's problem, check your installer.

**Comment by alichengyue** [comment]
thanks for your answer 
the node version is 8.1.3 
the npm version is 5.0.3
mac os 
but no work

**Comment by alichengyue** [comment]
sorry i have some wrong in package.json  sorry ~~
