### ISSUE TITLE
validate & body

### ISSUE THREAD

**Issue by Ailein** [koajs/bodyparser#82]
ctx.request.body 

the value will always return string type? right?

if i use the parameter  [https://github.com/node-modules/parameter](https://github.com/node-modules/parameter)

how to check number type?

![image](https://user-images.githubusercontent.com/26592729/28605409-1c61afe6-7204-11e7-89c3-21f0a1d1e1b6.png)

**Comment by dead-horse** [comment]
on, if your request's content type is `application/json`, it can won't always be string.
