### ISSUE TITLE
passing the returning value of next middleware through

### ISSUE THREAD

**Issue by coderfox** [koajs/bodyparser#83]
I think it is better to offer a option of passing through the returning value of the next middleware, as most applications may wrap a global error handler before all the middlewares. By providing such feature, we can do:

```javascript
koa.use(async (ctx,next) => {
  console.log("middleware returned",await next());
});
koa.use(bodyParser());
```

Which adds a lot flexibility to applications.

**Comment by dead-horse** [comment]
you can read request body from `ctx.request.body`
