### ISSUE TITLE
Does not play well with koa-compose

### ISSUE THREAD

**Issue by yadwinderpaul** [koajs/bodyparser#95]
App always sends `404 Not found` when `koa-bodyparser` is wrapped inside `koa-compose`

```json
{
    "koa": "^2.4.1",
    "koa-bodyparser": "^2.5.0",
    "koa-compose": "^4.0.0"
}
```

```javascript
const Koa = require('koa')
const compose = require('koa-compose')
const bodyparser = require('koa-bodyparser')

const app = new Koa()

// app.use(bodyparser()) // works
app.use(compose([bodyparser()])) // send 404

app.use((ctx) => {
  ctx.body = 'Hello World!'
})

app.listen(3000)
```

**Comment by dead-horse** [comment]
sorry, I can't get reproduction with your code. :(

**Comment by yadwinderpaul** [comment]
I am running:
```
macOS 10.13.2
Node v8.9.0
```

Even doesn't runs on:
```
Ubuntu 16.04.3 LTS
Node v8.1.4
```

**Comment by codinggirl** [comment]
This may should check other middleware's calling of `next()`.

If a middleware is a common function, we should call like:

```
next().then(() => {
    // any code here...
})
``` 
but not:

```
next()
```

I struggle this for several hours, so write it down, may it helps.

**Comment by sergeysova** [comment]
I have the same problem. And I was posted PR #102

**Comment by dead-horse** [comment]
@codinggirl koa-bodyparser's middleware is async function, so `await next()` is the same as `return next()` in this situation.

**Comment by sergeysova** [comment]
@dead-horse but in your case middleware return promise with undefined

**Comment by dead-horse** [comment]
I don't understand why middleware should return promise in this `koa-compose` case.

**Comment by fl0w** [comment]
This is issue is invalid.

@yadwinderpaul you're using an old version of koa-bodyparse which is not compliant with Koa 2 (and thus compose 4).

@codinggirl It makes no sense to break the promise flow with synchronous middleware currently. And not calling next is a completely valid use case. Having a guard in this repo (even though one could assume next is always called after this specific middleware) can be very confusing.
